import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  textoNombre: {
    color: 'black',
    fontFamily: 'arial',
    fontSize: 20,
    fontWeight: 'bold',
  },
  textoUbicacion: {
    fontFamily: 'arial',
    fontSize: 15,
  },
  textoPrecio: {
    color: 'red',
    fontFamily: 'arial',
    fontSize: 25,
    fontWeight: 'bold',
  },
  fondo: {
    backgroundColor: '#E0E0DE',
    width: '95%',
    height: 200,
    borderRadius: 15,
    margin: 11,
  },
  row: {
    flex: 1,
    flexDirection: 'row',
  },
  caja: {
    flex: 1,
    height: 180,
    backgroundColor: '#E0E0DE',
    margin: 5,
    borderRadius: 10,
  },
  tarjeta: {
    backgroundColor: '#E0E0DE',
    width: 40,
    height: 180,
    margin: 5,
    borderRadius: 10,
  },
  two: {
    flex: 1.5,
  },
  imagen: {
    width: 160,
    height: 180,
    borderRadius: 10,
  },
  estrella: {
    backgroundColor: '#E0E0DE',
    width: 60,
    height: 25,
    borderRadius: 10,
    alignItems: 'flex-end',
    justifyContent: 'center',
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'row',
    position: 'absolute',
    marginTop: 130,
  },
  nombre: {
    backgroundColor: '#E0E0DE',
    width: 235,
    height: 85,
    justifyContent: 'center',
    borderRadius: 10,
  },
  ubicacion: {
    backgroundColor: '#E0E0DE',
    width: 230,
    height: 35,
    alignItems: 'center',
    flexDirection: 'row',
    margin: 1,
    flex: 1,
  },
  box: {
    flex: 1,
    height: 30,
    backgroundColor: '#E0E0DE',
    borderRadius: 10,
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  box2: {
    backgroundColor: '#E0E0DE',
    alignItems: 'flex-end',
    flexDirection: 'row',
    borderRadius: 8,
  },
  box3: {
    backgroundColor: '#E0E0DE',
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  boxCora: {
    flex: 0.5,
    height: 40,
    backgroundColor: '#E0E0DE',
    borderRadius: 10,
    alignItems: 'flex-end',
    flexDirection: 'row-reverse',
    margin: 2,
  },
  icons: {
    width: 30,
    height: 30,
    margin: 5,
  },
  iconCora: {
    width: 40,
    height: 40,
    margin: 5,
  },
  iconUbicacion: {
    width: 15,
    height: 20,
  },
});
